### ISSUE TITLE
train_S3DIS.py error

### ISSUE THREAD

**Issue by narges-tk** [vLAR-group/GrowSP#13]
Hi! Thanks for sharing your code. 
I tried it for S3DIS dataset and am facing the following error when I ran the CUDA_VISIBLE_DEVICES=0, python train_S3DIS.py command:
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`.

![GrowSPerror](https://github.com/vLAR-group/GrowSP/assets/47797625/fc89f4f2-07df-4ef3-b30d-b502d7c889b5)

Thank you in advance for your help.

**Comment by zhang-zihui** [comment]
@narges-tk, Hi, seems the error occurred in MinkowskiEngine, did you keep the same virtual environment with us?

**Comment by narges-tk** [comment]
Yes, I have created the same virtual environment

**Comment by zhang-zihui** [comment]
Hi, @narges-tk, I guess the MinkowskiEngine may have some errors, you can try another installation:
Please install pytorch and other packages as illustrated in Readme. and activate the environment, then type the follow command to install MinkowskiEngine:
```shell script
git clone --recursive "https://github.com/NVIDIA/MinkowskiEngine"
cd MinkowskiEngine
git checkout 02fc608bea4c0549b0a7b00ca1bf15dee4a0b228
python setup.py install --force_cuda --blas=openblas 
```

**Comment by narges-tk** [comment]
Many thanks for your help! Now cuda error is resolved.
However, I am getting new following error related to numpy. I did not managed to fix it. Any suggestion is welcome.
Thanks in advance
![1](https://github.com/vLAR-group/GrowSP/assets/47797625/7d39b7e7-21bb-47e6-ada8-c3235d87edc9)
![2](https://github.com/vLAR-group/GrowSP/assets/47797625/dc2e6bae-62af-4bbf-a1d1-fe86e2547385)

**Comment by narges-tk** [comment]
I have solved the numpy error. However, I am facing the same cuda error again! Any help is greatly appreciated.
![1](https://github.com/vLAR-group/GrowSP/assets/47797625/65b4fcbe-a6bf-4c48-8869-af294d28b51d)

**Comment by zhang-zihui** [comment]
https://github.com/coqui-ai/TTS/issues/1517, this issue may provide some help, typing "unset LD_LIBRARY_PATH" in your python environment as https://github.com/coqui-ai/TTS/issues/1517#issuecomment-1437973294

**Comment by narges-tk** [comment]
Thanks, it is now resolved!

**Comment by jianGao555** [comment]
> 谢谢，现在已经解决了！

I have the same problem, can you provide a solution please?
